//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalHijosWS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class animalesCautiverio
    {
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public string Especie { get; set; }
        public string Edad { get; set; }
        public string RasgosUnicos { get; set; }
        public string LugarOrigen { get; set; }
        public string TipoHabitat { get; set; }
        public string Sexo { get; set; }
    }
}
